import { buildPlan, safeParsePlans } from './logic.js';
const $=s=>document.querySelector(s); const form=$('#shift-form'); let current=null; const STORAGE='heatshift-plans-v1';
function values(){const f=new FormData(form);return {shiftName:f.get('shiftName'),startTime:f.get('startTime'),duration:f.get('duration'),temperature:f.get('temperature'),humidity:f.get('humidity'),intensity:f.get('intensity'),sun:f.get('sun'),ppe:f.get('ppe'),acclimatized:f.get('acclimatized')==='on'};}
function defaults(){const now=new Date();now.setMinutes(Math.ceil(now.getMinutes()/15)*15);form.elements.startTime.value=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()%60).padStart(2,'0')}`;form.elements.duration.value='8';form.elements.temperature.value='30';form.elements.humidity.value='55';}
function render(plan){current=plan;$('#empty-result').hidden=true;$('#result').hidden=false;$('#result-title').textContent=plan.shiftName;const badge=$('#tier-badge');badge.textContent=plan.label;badge.className=`tier-badge tier-${plan.tier}`;$('#result-summary').textContent=plan.summary;$('#heat-index').textContent=`${plan.heatIndex}°C`;$('#check-in').textContent=`Every ${plan.check} min`;$('#review-time').textContent=`Every ${plan.review} min`;$('#callout').textContent=plan.callout;$('#checklist').replaceChildren(...plan.checklist.map((item,i)=>{const label=document.createElement('label');label.className='check-item';const box=document.createElement('input');box.type='checkbox';box.setAttribute('aria-label',item);const span=document.createElement('span');span.textContent=item;label.append(box,span);return label;}));$('#timeline').replaceChildren(...plan.timeline.map(x=>{const el=document.createElement('div');el.className='timeline-item';const strong=document.createElement('strong');strong.textContent=x.time;const span=document.createElement('span');span.textContent=x.label;el.append(strong,span);return el;}));}
function plans(){return safeParsePlans(localStorage.getItem(STORAGE)||'[]');}function persist(items){localStorage.setItem(STORAGE,JSON.stringify(items));$('#save-status').textContent='Saved on this device';renderSaved();}
function renderSaved(){const items=plans(),wrap=$('#saved-plans');if(!items.length){wrap.innerHTML='<div class="saved-empty">No saved plans yet. Build one above, then save it for the next briefing.</div>';return;}wrap.replaceChildren(...items.map((plan,index)=>{const card=document.createElement('article');card.className='saved-card';const h=document.createElement('h3');h.textContent=plan.shiftName;const p=document.createElement('p');p.textContent=`${plan.startTime} · ${plan.duration}h · ${plan.heatIndex}°C estimated heat index · ${plan.label}`;const open=document.createElement('button');open.className='button secondary small';open.textContent='Open';open.onclick=()=>{render(plan);location.hash='planner';};const del=document.createElement('button');del.className='text-button danger';del.textContent='Delete';del.onclick=()=>{const next=plans();next.splice(index,1);persist(next);};card.append(h,p,open,del);return card;}));}
form.addEventListener('submit',e=>{e.preventDefault();const error=$('#form-error');error.hidden=true;try{render(buildPlan(values()));}catch(err){error.textContent=err.message;error.hidden=false;error.scrollIntoView({behavior:'smooth',block:'center'});}});form.addEventListener('reset',()=>setTimeout(()=>{defaults();current=null;$('#result').hidden=true;$('#empty-result').hidden=false;$('#form-error').hidden=true;},0));
$('#load-sample').onclick=()=>{Object.assign(form.elements.shiftName,{value:'Community garden — afternoon setup'});form.elements.startTime.value='13:00';form.elements.duration.value='4';form.elements.temperature.value='34';form.elements.humidity.value='68';form.elements.intensity.value='moderate';form.elements.sun.value='direct';form.elements.ppe.value='standard';form.elements.acclimatized.checked=false;render(buildPlan(values()));location.hash='planner';};
$('#save-plan').onclick=()=>{if(!current)return;const items=plans();items.unshift({...current,id:crypto.randomUUID()});persist(items.slice(0,25));};$('#print-plan').onclick=()=>window.print();
$('#export-data').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),plans:plans()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='heatshift-plans.json';a.click();URL.revokeObjectURL(a.href);};
$('#clear-data').onclick=()=>{if(confirm('Delete every HeatShift plan stored in this browser?')){localStorage.removeItem(STORAGE);renderSaved();}};
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install-button').hidden=false;});$('#install-button').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install-button').hidden=true;}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{$('#save-status').textContent='Offline setup unavailable';});defaults();renderSaved();
